# Generated by Django 3.2.2 on 2021-05-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddfds', upload_to='pics'),
            preserve_default=False,
        ),
    ]
